/*
Enter your query here.
SELECT DISTINCT CITY FROM STATION WHERE  CITY LIKE '%[aeiou]' AND CITY LIKE '[aeiou]%'; (didn't work but it should)

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE '(aeiou)%' AND CITY LIKE '%(aeiou)';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'e%' AND CITY LIKE '%e';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'i%' AND CITY LIKE '%i';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'o%' AND CITY LIKE '%o';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'u%' AND CITY LIKE '%u';

SELECT * FROM Customers
WHERE Country IN (SELECT Country FROM Suppliers);
*/
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%' AND CITY LIKE '%a';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%' AND CITY LIKE '%e';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%' AND CITY LIKE '%i';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%' AND CITY LIKE '%o';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'a%' AND CITY LIKE '%u';

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'e%' AND CITY LIKE '%a';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'e%' AND CITY LIKE '%e';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'e%' AND CITY LIKE '%i';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'e%' AND CITY LIKE '%o';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'e%' AND CITY LIKE '%u';

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'i%' AND CITY LIKE '%a';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'i%' AND CITY LIKE '%e';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'i%' AND CITY LIKE '%i';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'i%' AND CITY LIKE '%o';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'i%' AND CITY LIKE '%u';

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'o%' AND CITY LIKE '%a';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'o%' AND CITY LIKE '%e';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'o%' AND CITY LIKE '%i';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'o%' AND CITY LIKE '%o';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'o%' AND CITY LIKE '%u';

SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'u%' AND CITY LIKE '%a';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'u%' AND CITY LIKE '%e';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'u%' AND CITY LIKE '%i';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'u%' AND CITY LIKE '%o';
SELECT DISTINCT CITY FROM STATION WHERE CITY LIKE 'u%' AND CITY LIKE '%u';